name: CI
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build
        uses: actions/docker/cli@8cdf801b322af5f369e00d85e9cf3a7122f49108
        with:
          args: build --target build -t co0sh/hexagon-ui:dev .
      - name: Test
        uses: actions/docker/cli@8cdf801b322af5f369e00d85e9cf3a7122f49108
        with:
          args: run --rm co0sh/hexagon-ui:dev npm run test
      - name: Lint
        uses: actions/docker/cli@8cdf801b322af5f369e00d85e9cf3a7122f49108
        with:
          args: run --rm co0sh/hexagon-ui:dev npm run lint
      - name: Style
        uses: actions/docker/cli@8cdf801b322af5f369e00d85e9cf3a7122f49108
        with:
          args: run --rm co0sh/hexagon-ui:dev npm run style
      - name: Login
        uses: actions/docker/login@8cdf801b322af5f369e00d85e9cf3a7122f49108
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      - name: Release
        uses: actions/docker/cli@8cdf801b322af5f369e00d85e9cf3a7122f49108
        with:
          args: build -t co0sh/hexagon-ui:latest .
      - name: Push
        uses: actions/docker/cli@8cdf801b322af5f369e00d85e9cf3a7122f49108
        with:
          args: push co0sh/hexagon-ui:latest
      - name: Deploy
        uses: maddox/actions/ssh@master
        env:
          HOST: ${{ secrets.HOST }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          USER: ${{ secrets.USER }}
        with:
          args: ~/deploy-ui.sh
